repos:
  - hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - manual
    repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
  - hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
    repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
